name: CI
on: [push, pull_requests]
jobs:
  dockerLint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Docker Lint
      uses: docker://replicated/dockerfilelint
      with:
        args: Dockerfile
    - name: swift test
      uses: docker://norionomura/swiftlint
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        entrypoint: swift
        args: test
    - name: Docker Build
      uses: actions/docker/cli@master
      with:
        args: build -t action-swiftlint .
